### ISSUE TITLE
horovodrun: command not found

### ISSUE THREAD

**Issue by ktamiola** [horovod/horovod#1045] opened 2019-05-02 23:31 UTC
Ladies and gentlemen.

This one is very simple. I have just installed version `0.16.1`. All looked fine. No compilation issues. I was also able to launch Keras demos in single GPU mode.

However, it seems `horovodrun` was not bundled with my installation. Are you also missing `horovodrun` in `0.16.1` ?

My system Ubuntu `18.04.1` with Python `2.7.15rc1`.

**Comment by abditag2** [comment] 2019-05-02 23:37
No, horovodrun should come with version 0.16.1. Did you install using pip? If you are using virtual environment, check your `<path to venv>/bin/`. 
Check `find /usr/local/bin | grep horovod*` as well.

**Comment by ktamiola** [comment] 2019-05-02 23:39
Cheers. I have installed using `HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod`.

It seems `horovod` is nowhere to be found.

**Comment by abditag2** [comment] 2019-05-02 23:41
are you using a virtual environment?

**Comment by ktamiola** [comment] 2019-05-02 23:41
I am not using virtual environment. For the record.

**Comment by ThrowMeForALoop** [comment] 2019-05-03 14:45
Maybe you can replace "horovodrun" with "mpirun". It works for me

**Comment by ktamiola** [comment] 2019-05-04 12:23
One can copy the source code of `horovodrun` and make an executable out of it. My concern is the `horovodrun` seems not to be bundled with the pip package.

**Comment by alsrgv** [comment] 2019-05-07 09:54
@ktamiola, what's your `pip --version`?  Can you try `pip install -U pip`, followed by a reinstall of Horovod?

**Comment by Young768** [comment] 2019-05-14 17:59
@alsrgv Hi alex. I am using pip 19.1.1. I met the same issues. Everything looks good yesterday and I can run examples. I tried horovodrun this morning. But it shows command not found. It looks so strange.

**Comment by alsrgv** [comment] 2019-05-15 00:50
@Young768, did you resolve with missing `horovodrun` issue?

**Comment by Young768** [comment] 2019-05-15 00:55
@alsrgv Yes. When I entered the base environment, the problem is resolved.

**Comment by 7LFB** [comment] 2019-05-27 12:36
> No, horovodrun should come with version 0.16.1. Did you install using pip? If you are using virtual environment, check your `<path to venv>/bin/`.
> Check `find /usr/local/bin | grep horovod*` as well.

hello, I installed the horovod using pip, but cant find 'horovodrun'. what should I do?

**Comment by alsrgv** [comment] 2019-05-29 03:56
@7LFB, can you try installing Horovod in virtualenv?

**Comment by 7LFB** [comment] 2019-05-29 04:46
yep, I installed Horovod in virturalenv created by conda. and  i cant find any horovodrun file.  But it works using mpirun command.

**Comment by alsrgv** [comment] 2019-05-29 06:04
@7LFB, I wonder if Conda introduces any magic. Can you try a pure virtualenv?

**Comment by mtrimmel** [comment] 2020-04-01 14:08
Hello, I am having the same problem: `horovodrun -np 2 -H localhost:2 python train.py` returns `horovodrun: command not found`.
Horovod 0.13.8, Tensorflow 1.8, Ubuntu 16.4, Python 3.6.9, pip 20.0.2.
I am trying to run on 2 GPUs on my local machine. As suggested above by @alsrgv, I have made sure to use the latest pip version to install Horovod. I used Pycharm for the installation of Horovod. I am **not** using Conda. I can find Horovod neither in `venv/bin` nor in `/usr/local/bin`, but there are folders `horovod` and `horovod-0.13.8.dist-info` in `venv/lib/python3.6/site-packages` and in `venv/lib64/python3.6/site-packages`.

**Comment by tgaddair** [comment] 2020-04-01 15:15
Hey @martin294, `horovodrun` was introduced in Horovod version `0.18`.  Can you try upgrading to a more recent version?  Otherwise, I would suggesting using [mpirun](https://github.com/horovod/horovod/blob/master/docs/mpirun.rst) instead.

**Comment by martin294** [comment] 2020-04-01 17:31
Thanks a lot, that solves my problem! 👍

**Comment by b1ueshad0w** [comment] 2020-10-28 16:47
On Ubuntu binaries from python packge will be installed to `${HOME}/.local/bin`. Simply add "export PATH=${HOME}/.local/bin:$PATH" into `.bashrc` file and `source .bashrc` will fix this issue!

**Closed** 2021-01-03 18:02 UTC
Labels: question, wontfix
