### ISSUE TITLE
Could not resolve hostname

### ISSUE THREAD

**Issue by haif-liu** [horovod/horovod#1032] opened 2019-04-29 04:05 UTC
the version of openmpi is 4.0.0.

horovodrun -np 1 -H localhost:1 python test.py

ssh: Could not resolve hostname localhost:1: Temporary failure in name resolution
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

not finding the required libraries and/or binaries on
one or more nodes. Please check your PATH and LD_LIBRARY_PATH
settings, or configure OMPI with --enable-orterun-prefix-by-default

lack of authority to execute on one or more specified nodes.
Please verify your allocation and authorities.

the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
Please check with your sys admin to determine the correct location to use.

compilation of the orted with dynamic libraries when static are required
(e.g., on Cray). Please check your configure cmd line and consider using
one of the contrib/platform definitions for your system type.

an inability to create a connection back to mpirun due to a
lack of common network interfaces and/or no route found between
them. Please check network connectivity (including firewalls
and network routing requirements).

**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

**Comment by alsrgv** [comment] 2019-04-29 22:58
@haif-liu, were you able to resolve this issue?  If not, can you do `find /usr | grep mpirun` to see if you have multiple versions of MPI installed?

**Comment by haif-liu** [comment] 2019-04-30 01:38
command: find /usr | grep mpirun

/usr/share/man/man1/mpirun.1.gz
/usr/share/man/man1/mpirun.openmpi.1.gz
/usr/lib/openmpi/include/openmpi/ompi/runtime/mpiruntime.h
/usr/bin/mpirun.openmpi
/usr/bin/mpirun


> @haif-liu, were you able to resolve this issue? If not, can you do `find /usr | grep mpirun` to see if you have multiple versions of MPI installed?

**Comment by alsrgv** [comment] 2019-04-30 02:04
@haif-liu, and what's the output of `mpirun --version`?

**Comment by heartbeat2015** [comment] 2019-05-13 09:03
@haif-liu I came into exactly the same issue,have you solve this?

**Comment by alsrgv** [comment] 2019-05-13 09:05
@heartbeat2015, the most common cause for `Could not resolve hostname <something>:<number>` is an old Open MPI version.

**Comment by heartbeat2015** [comment] 2019-05-13 09:10
@alsrgv my openmpi version is 4.0.0 ,and when put the  mpirun -V ,I get the version 1.10.2,is that right verison?

**Comment by alsrgv** [comment] 2019-05-13 09:15
@heartbeat2015, no - it means your Open MPI version is 1.10.2.  It can happen if you have two versions of MPI for some reason.  Can you check `dpkg -l | grep openmpi` if you're using Ubuntu or Debian?

**Comment by heartbeat2015** [comment] 2019-05-13 09:21
@alsrgv output of  dpkg -l | grep openmpi  is: 

ii  libopenmpi-dev           1.10.2-8ubuntu1   amd64             high performance message passing library -- header fil
ii  libopenmpi1.10           1.10.2-8ubuntu1   amd64             high performance message passing library -- shared lib
ii  openmpi-bin              1.10.2-8ubuntu1   amd64             high performance message passing library -- binaries
ii  openmpi-common           1.10.2-8ubuntu1   all               high performance message passing library -- common fil

ok,I think I know what's the problem,thanks : )

**Comment by heartbeat2015** [comment] 2019-05-13 13:31
@alsrgv  I reinstall the openmpi-4.0.0,but another error came when I run   horovodrun -np 1 -H localhost:1 python pytorch_horovod_mnist.py

ImportError: libmpi_cxx.so.1: cannot open shared object file: No such file or directory

I can't find this lib(libmpi_cxx.so.1) in the openmpi-4.0.0/lib directory,but the lower version ,i.e. version 1.10,this lib is accessable.
my horovod version is 0.16
pytorch version is 0.4.0
any incompatibility?

**Comment by abditag2** [comment] 2019-05-13 16:56
Could you please post the result of `ldconfig -p | grep -i mpi`?

**Comment by heartbeat2015** [comment] 2019-05-14 03:10
@abditag2  the output of  ldconfig -p | grep -i mpi :

libopen-rte.so.40 (libc6,x86-64) => /opt/openmpi/lib/libopen-rte.so.40
        libopen-rte.so (libc6,x86-64) => /opt/openmpi/lib/libopen-rte.so
        libopen-pal.so.40 (libc6,x86-64) => /opt/openmpi/lib/libopen-pal.so.40
        libopen-pal.so (libc6,x86-64) => /opt/openmpi/lib/libopen-pal.so
        libompitrace.so.40 (libc6,x86-64) => /opt/openmpi/lib/libompitrace.so.40
        libompitrace.so (libc6,x86-64) => /opt/openmpi/lib/libompitrace.so
        libnvidia-ptxjitcompiler.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1
        libnvidia-compiler.so.410.104 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.410.104
        libmpi_usempif08.so.40 (libc6,x86-64) => /opt/openmpi/lib/libmpi_usempif08.so.40
        libmpi_usempif08.so (libc6,x86-64) => /opt/openmpi/lib/libmpi_usempif08.so
        libmpi_usempi_ignore_tkr.so.40 (libc6,x86-64) => /opt/openmpi/lib/libmpi_usempi_ignore_tkr.so.40
        libmpi_usempi_ignore_tkr.so (libc6,x86-64) => /opt/openmpi/lib/libmpi_usempi_ignore_tkr.so
        libmpi_mpifh.so.40 (libc6,x86-64) => /opt/openmpi/lib/libmpi_mpifh.so.40
        libmpi_mpifh.so (libc6,x86-64) => /opt/openmpi/lib/libmpi_mpifh.so
        libmpi.so.40 (libc6,x86-64) => /opt/openmpi/lib/libmpi.so.40
        libmpi.so (libc6,x86-64) => /opt/openmpi/lib/libmpi.so
        libmca_common_verbs.so.40 (libc6,x86-64) => /opt/openmpi/lib/libmca_common_verbs.so.40
        libmca_common_verbs.so (libc6,x86-64) => /opt/openmpi/lib/libmca_common_verbs.so
        libmca_common_sm.so.40 (libc6,x86-64) => /opt/openmpi/lib/libmca_common_sm.so.40
        libmca_common_sm.so (libc6,x86-64) => /opt/openmpi/lib/libmca_common_sm.so
        libmca_common_ompio.so.41 (libc6,x86-64) => /opt/openmpi/lib/libmca_common_ompio.so.41
        libmca_common_ompio.so (libc6,x86-64) => /opt/openmpi/lib/libmca_common_ompio.so
        libmca_common_monitoring.so.50 (libc6,x86-64) => /opt/openmpi/lib/libmca_common_monitoring.so.50
        libmca_common_monitoring.so (libc6,x86-64) => /opt/openmpi/lib/libmca_common_monitoring.so

**Comment by alsrgv** [comment] 2019-05-14 06:35
@heartbeat2015, after you've fixed Open MPI installation, can you uninstall Horovod and reinstall with `--no-cache-dir`?

**Comment by heartbeat2015** [comment] 2019-05-15 06:52
@alsrgv  I follow your hints ,reinstall horovod by  

HOROVOD_NCCL_HOME=/opt/nccl 
HOROVOD_GPU_ALLREDUCE=NCCL
pip install --no-cache-dir horovod

Now, I can run  horovodrun -np 1 -H localhost:1 python pytorch_horovod_mnist.py
and two gpus on one machine as well
But when I use two machines,each have one gpu,run the command:   horovodrun -np 2 -H 192.168.6.9:1,192.168.1.4:1 python pytorch_horovod_mnist.py
error happen again.It putout:

Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 21, in <module>
    run.run()
  File "/usr/local/lib/python3.5/dist-packages/horovod/run/run.py", line 418, in run
    fn_cache=fn_cache)
  File "/usr/local/lib/python3.5/dist-packages/horovod/run/util/cache.py", line 103, in wrap_f
    results = func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/horovod/run/run.py", line 237, in _driver_fn
    for index in range(num_hosts)]
  File "/usr/local/lib/python3.5/dist-packages/horovod/run/run.py", line 237, in <listcomp>
    for index in range(num_hosts)]
  File "/usr/local/lib/python3.5/dist-packages/horovod/run/task/task_service.py", line 72, in __init__
    retries=retries)
  File "/usr/local/lib/python3.5/dist-packages/horovod/run/common/service/task_service.py", line 133, in __init__
    retries=retries)
  File "/usr/local/lib/python3.5/dist-packages/horovod/run/common/util/network.py", line 161, in __init__
    self._addresses = self._probe(addresses)
  File "/usr/local/lib/python3.5/dist-packages/horovod/run/common/util/network.py", line 170, in _probe
    for intf, intf_addresses in addresses.items():
AttributeError: 'NoneType' object has no attribute 'items'

horovod version is 0.16.1

**Comment by iblanque** [comment] 2019-05-15 07:59
Hi, I think that the problem is in OpenMPI. I installed version 4.0.1 and I have this problem even running a basic MPI program. The interesting thing is that MPI is ignoring the full domain and it uses only the hostname, as it can be seen with the example:
mpiexec -np 2 --allow-run-as-root  --host clusterworker-1.mpicluster.default.svc.cluster.local,clusterworker-0.mpicluster.default.svc.cluster.local /mnt/share/vol001/mpitest41
ssh: Could not resolve hostname clusterworker-0: Name or service not known

This is solved by adding a line link this:
<<IP>>	clusterworker-1.mpicluster.default.svc.cluster.local	clusterworker-1

in /etc/hosts. 

mpiexec -np 2 --allow-run-as-root -v --host clusterworker-1.mpicluster.default.svc.cluster.local,clusterworker-0.mpicluster.default.svc.cluster.local /mnt/share/vol001/mpitest41 
Hello world, I am process number: 0 on host clusterworker-1
Hello world, I am process number: 1 on host clusterworker-0

I believe the above problem may be solved by using localhost.localdomain instead of localhost only. 

We may send this issue to OpenMPI then.

**Comment by alsrgv** [comment] 2019-05-15 08:09
@iblanque, thanks for noting this.  Another solution could be to add `search mpicluster.default.svc.cluster.local` to `/etc/resolv.conf`.

@heartbeat2015, could you share the output of `ifconfig -a` from both machines?  Are they on the same network?

**Comment by alsrgv** [comment] 2019-05-15 08:34
@heartbeat2015, we'd like to add self-diagnostic functionality to `horovodrun` for this issue, could you reinstall it via `[flags] pip install --no-cache-dir git+https://github.com/horovod/horovod@horovodrun_fixes` and run the command again?

**Comment by heartbeat2015** [comment] 2019-05-15 09:35
@alsrgv 
I can ping through each other,but they are not on the same LAN.
Is it matter?

And,you mean uninstall horovod first,then 
pip install --no-cache-dir git+https://github.com/horovod/horovod@horovodrun_fixes
but I seem to stuck, what's the @horovodrun_fixes mean?

machine 0:

eth0      Link encap:Ethernet  HWaddr 02:42:c0:a8:06:09
          inet addr:192.168.6.9  Bcast:192.168.6.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1472  Metric:1
          RX packets:3607 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3291 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2062877 (2.0 MB)  TX bytes:3553793 (3.5 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:103 errors:0 dropped:0 overruns:0 frame:0
          TX packets:103 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:27496 (27.4 KB)  TX bytes:27496 (27.4 KB)
		  
		  
machine 1:

eth0      Link encap:Ethernet  HWaddr 02:42:c0:a8:01:04
          inet addr:192.168.1.4  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1472  Metric:1
          RX packets:28931 errors:0 dropped:0 overruns:0 frame:0
          TX packets:24169 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:53155106 (53.1 MB)  TX bytes:5042342 (5.0 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:124 errors:0 dropped:0 overruns:0 frame:0
          TX packets:124 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:39022 (39.0 KB)  TX bytes:39022 (39.0 KB)

**Comment by alsrgv** [comment] 2019-05-15 18:11
@heartbeat2015, it does matter - it seems like they're behind NAT which is not supported.

Could you uninstall Horovod and reinstall using `[flags] pip install --no-cache-dir git+https://github.com/horovod/horovod@horovodrun_fixes`?  That's a branch of the #1076 fix.  It's available until the PR is merged, after which it will be available in @master.

**Comment by heartbeat2015** [comment] 2019-05-17 01:37
@alsrgv why NAT matter and any solution? my cluster is on different nodes where they doesn't on the same LAN,I seems have to solve this problem. Reasonable, cluster can communicate with each other with basic connection.

**Comment by alsrgv** [comment] 2019-05-17 01:43
@heartbeat2015, nodes in the cluster must be able to reach each other, and NAT generally makes it hard. You can try using `mpirun` directly instead of `horovodrun` by following [this doc](https://github.com/horovod/horovod/blob/update_docs/docs/mpirun.rst).

**Comment by heartbeat2015** [comment] 2019-05-17 05:30
@alsrgv  I get two machine on the same LAN ,and using
horovodrun -np 2 -H 192.168.1.3:1,192.168.1.4:1 python pytorch_horovod_mnist.py
the output is:

start at port: 60390

abc {'lo': [('127.0.0.1', 59685)], 'eth0': [('192.168.1.4', 59685)]} 1
{'lo': [('127.0.0.1', 59685)], 'eth0': [('192.168.1.4', 59685)]} : 127.0.0.1
abc {'lo': [('127.0.0.1', 47482)], 'eth0': [('192.168.1.3', 47482)]} 0
{'lo': [('127.0.0.1', 47482)], 'eth0': [('192.168.1.3', 47482)]} : 192.168.1.3
('192.168.1.3', 47482)
('192.168.1.4', 59685)
bash: orted: command not found
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
It is the error in mpi. And I follow the doc run mpi,using
mpirun --allow-run-as-root -np 2 \
	-H 192.168.6.9:1,192.168.1.4:1 \
    -bind-to none -map-by slot \
	-x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl ^openib \
    python pytorch_horovod_mnist.py
It output the same error as above.
 
env:
openmpi 4.0.0

ps:
I found some solution on the internet,but didn't work.
i.e. config ~/.bashrc add environment variable
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/openmpi/lib
export PATH=$PATH:/opt/openmpi/bin

**Comment by alsrgv** [comment] 2019-05-17 06:58
@heartbeat2015, progress!  Can you try building Open MPI like we do [here](https://github.com/horovod/horovod/blob/master/Dockerfile#L40), with the `--enable-orterun-prefix-by-default` option?

**Comment by ParkGeonYeong** [comment] 2019-09-15 14:51
@alsrgv Hello, i have exactly same problem with @heartbeat2015 , and i'm willing to install openmpi with ver 4.0.0 again. Now i have mpirun version 1.10.2 which seems to be my default one in ubuntu 16.04

How should i reinstall or overwrite new version over 1.10.2? Should i remove the old default one? Open MPI team recommends to install another path, such as /opt/openmpi-<version>. Then how should i reinstall horovod with that new version?

**Closed** 2020-11-14 01:48 UTC
Labels: question, wontfix
