### ISSUE TITLE
This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock

### ISSUE THREAD

**Issue by SicleBoypy** [horovod/horovod#2640] opened 2021-02-02 04:00 UTC
[0]<stderr>:[haoweilai 2021-02-02 03:22:16,448 (trainer:514) INFO: 3epoch:train:99-112batch: iter_time=8.416e-05, forward_time=0.162, loss=84.699, loss_att=79.672, loss_ctc=96.430, acc=0.105, backward_time=0.152, optim_step_time=0.310, lr_0=5.750e-05, train_time=5.510
[0]<stderr>:[2021-02-02 03:23:51. 70957: W /tmp/pip-install-wztcejga/horovod_5b3931a7e1ed48ce93cf2eda4263910e/horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock.
[0]<stderr>:Missing ranks:
[0]<stderr>:0: [allreduce.noname.222700]
[0]<stderr>:1: [allreduce.noname.222700]
[0]<stderr>:2: [allreduce.noname.222700]
[0]<stderr>:3: [allreduce.noname.222700]
[0]<stderr>:4: [allreduce.noname.222700]
[0]<stderr>:5: [allreduce.noname.222700]
[0]<stderr>:6: [allreduce.noname.222700]
[0]<stderr>:7: [allreduce.noname.222700]
[0]<stderr>:8: [allreduce.noname.222700]
[0]<stderr>:9: [allreduce.noname.222700]
[0]<stderr>:10: [allreduce.noname.222700]
[0]<stderr>:11: [allreduce.noname.222700]
[0]<stderr>:12: [allreduce.noname.222700]
[0]<stderr>:13: [allreduce.noname.222700]
[0]<stderr>:14: [allreduce.noname.222700]
[0]<stderr>:[2021-02-02 03:24:51. 79803: W /tmp/pip-install-wztcejga/horovod_5b3931a7e1ed48ce93cf2eda4263910e/horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock.
[0]<stderr>:Missing ranks:
[0]<stderr>:0: [allreduce.noname.222700]
[0]<stderr>:1: [allreduce.noname.222700]

when using single node , it works normally. but when using  
        HOROVOD_CACHE_CAPACITY=8192 horovodrun -np 16 --gloo --autotune \
            -H 10.19.250.170:8,10.19.250.171:8 \
            -p 22 python ...
it cause deadlock. how to solve it?

**Comment by tgaddair** [comment] 2021-02-03 15:51
Hey @SicleBoypy, this is usually a scripting error caused by having imbalanced data.  In this case, it appears that rank 15 (not listed as missing) is making on more allreduce calls than the other workers.  Can you verify that every worker is processing the same number of batches?

**Comment by SicleBoypy** [comment] 2021-02-04 07:18
> 
> 
> Hey @SicleBoypy, this is usually a scripting error caused by having imbalanced data. In this case, it appears that rank 15 (not listed as missing) is making on more allreduce calls than the other workers. Can you verify that every worker is processing the same number of batches?

Hey @tgaddair ，Thanks for your replying，but I also have a question about it. When rank 15 spends more time on woking more data(minibatch larger than others), all ranks should wait for rank 15 ,then synchronized allreduce. when appearing this error, which allreduce using? synchronized or asynchronized ?

**Comment by SicleBoypy** [comment] 2021-02-04 07:20
> 
> 
> Hey @SicleBoypy, this is usually a scripting error caused by having imbalanced data. In this case, it appears that rank 15 (not listed as missing) is making on more allreduce calls than the other workers. Can you verify that every worker is processing the same number of batches?

**Comment by SicleBoypy** [comment] 2021-02-04 07:31
> 
> 
> Hey @SicleBoypy, this is usually a scripting error caused by having imbalanced data. In this case, it appears that rank 15 (not listed as missing) is making on more allreduce calls than the other workers. Can you verify that every worker is processing the same number of batches?

Hey @tgaddair ，Thanks for your replying，but I also have a question about it. When rank 15 spends more time on woking more data(minibatch larger than others), all ranks should wait for rank 15 ,then synchronized allreduce. when appearing this error, which allreduce using? synchronized or asynchronized ?

I also meet another question:

[24]<stderr>:RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

It appears to that one of the ranks has finished the task, but one of the ranks attempt to allreduce, allgather or broadcast. this error happens to the demo for mnist which has the same batch. it seem that asynchronized  allreduce in horovod. but asynchronized training will has the error gradient allreduce ，isn't it？

**Comment by tgaddair** [comment] 2021-02-08 22:45
@SicleBoypy, Horovod aggregates gradients in a synchronous manner, so all workers send/receive gradients before moving on to the next batch.  When these types of errors occur, it usually means that one of the workers is attempting to send/receive gradients when the others are not, which is not allowed.

However, it shouldn't happen with the MNIST example.  Can you share the full command you're using to run?

**Comment by SicleBoypy** [comment] 2021-02-09 02:45
> 
> 
> @SicleBoypy, Horovod aggregates gradients in a synchronous manner, so all workers send/receive gradients before moving on to the next batch. When these types of errors occur, it usually means that one of the workers is attempting to send/receive gradients when the others are not, which is not allowed.
> 
> However, it shouldn't happen with the MNIST example. Can you share the full command you're using to run?

@tgaddair my command is that  "horovodrun -np 8 -H 10.19.250.182:2,10.19.250.183:2,10.19.250.170:2,10.19.250.171:2 -p 22 --gloo python pytorch_mnist.py 2>&1|tee train.log"
[train.log](https://github.com/horovod/horovod/files/5948359/train.log)

Thanks your replying. I have a task that all ranks has same the num of batch, but batch size may different. The batchsize of rank15 is 64, but other ranks is 32. Others will faster than rank15, In this situation, others will wait for rank15  make synchronous allreduce, isn't it? If true, when the batchsize of rank15 is very large, such as 1024,2048 and so on, others will still wait for rank 15 util it has finished. Is what I think is correct ？Thanks

**Comment by tgaddair** [comment] 2021-02-11 15:57
Is it possible to have rank15 run with the same batch size as the others?  Otherwise, rank15 will be processing twice as much data per step, which will affect a number of things.

**Comment by SicleBoypy** [comment] 2021-02-20 03:30
> 
> 
> Is it possible to have rank15 run with the same batch size as the others? Otherwise, rank15 will be processing twice as much data per step, which will affect a number of things.

OK，Thanks your advice，I will keep the same batchsize for all ranks. But the  mnist training has same batchsize for all ranks, why it happens error finally?

**Comment by tgaddair** [comment] 2021-02-20 16:41
Hey @SicleBoypy, I thought the script you were running was modified so different ranks had different batch sizes, but maybe I misunderstood. Are you saying this error happens even with the unmodified script in Horovod's examples directory?

**Comment by SicleBoypy** [comment] 2021-02-25 11:31
> 
> 
> Hey @SicleBoypy, I thought the script you were running was modified so different ranks had different batch sizes, but maybe I misunderstood. Are you saying this error happens even with the unmodified script in Horovod's examples directory?

Thanks，I found the code difference in two node and solved the problem.

**Comment by tgaddair** [comment] 2021-02-25 20:55
Awesome! I'll go ahead and close this issue then.

**Closed by tgaddair** 2021-02-25 20:55 UTC
Labels: question
