### ISSUE TITLE
hvd.keras_estimator.fit() throws Py4JJavaError caused by java.io.IOException

### ISSUE THREAD

**Issue by orwa-te** [horovod/horovod#2029] opened 2020-06-15 21:19 UTC
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): Tensorflow
2. Framework version: 2.1.0
3. Horovod version: 0.19.4
4. MPI version: 4.0.3
5. CUDA version: None
6. NCCL version: None
7. Python version: 3.7.0
8. OS and version: Ubuntu 20
9. GCC version: 9.3.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
I am trying to execute the example linked at [keras_spark_mnist.py](https://github.com/horovod/horovod/blob/master/examples/keras_spark_mnist.py) on my standalone Spark cluster which is an only single machine with 10 GB Ram and has one worker on the same machine.
After a few seconds of execution, I get an error at line 114 "**keras_model = keras_estimator.fit(train_df).setOutputCols(['label_prob'])**" described below:

"Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob. : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 4.0 failed 4 times, most recent failure: Lost task 0.3 in stage 4.0 (TID 9, 192.168.198.131, executor 0): java.io.IOException: Cannot run program "python": error=2, No such file or directory"

What could be the problem? How do I solve it?

**Comment by EnricoMi** [comment] 2020-06-16 12:00
Hi Orwa,

how do you launch that script (e.g. `python keras_spark_mnist.py` or `spark-submit`), can you give me the command line?

Did you try to set `PYSPARK_PYTHON` to the full path of the python binary that you are using for your keras example script?

Can you run the following `pyspark` connecting to your standalone cluster?

```
pyspark --master "..."
>>> spark.range(5).show()
+---+
| id|
+---+
|  0|
|  1|
|  2|
|  3|
|  4|
+---+
```

**Comment by orwa-te** [comment] 2020-06-16 20:32
> Hi Orwa,
> 
> how do you launch that script (e.g. `python keras_spark_mnist.py` or `spark-submit`), can you give me the command line?
> 
> Did you try to set `PYSPARK_PYTHON` to the full path of the python binary that you are using for your keras example script?
> 
> Can you run the following `pyspark` connecting to your standalone cluster?
> 
> ```
> pyspark --master "..."
> >>> spark.range(5).show()
> +---+
> | id|
> +---+
> |  0|
> |  1|
> |  2|
> |  3|
> |  4|
> +---+
> ```

Hello EnricoMi, Thanks for your reply.
Command used to launch the program is `spark-submit --master spark://192.168.198.131:7077 keras_spark_mnist.py`, also tried using Jupyter Notebook and got the same result.
Anaconda is installed and I enter my virtual environment(python=3.7.0) before executing the program so that I guess PYSPRAK_PYTHON is not needed to be configured in spark-env.sh 

I executed `spark.range(5).show()` and got the same output without any problem

**Comment by EnricoMi** [comment] 2020-06-16 20:39
Let me try to reproduce this.

**Comment by EnricoMi** [comment] 2020-06-17 08:07
Sorry, I cannot reproduce this with my standalone Spark cluster.

Can you please do the following things:

- Run `env PYSPRAK_PYTHON=PATH/TO/VENV/bin/python spark-submit --master spark://192.168.198.131:7077 keras_spark_mnist.py`.
- Change `verbose=1` for `hvd.KerasEstimator` to `verbose=3` in `keras_spark_mnist.py` and watch out for `Task service executes command:` log messages and the environment variables used for that command (probably in the executors' stderr log).

Thanks

**Comment by orwa-te** [comment] 2020-06-17 18:22
> Sorry, I cannot reproduce this with my standalone Spark cluster.
> 
> Can you please do the following things:
> 
> * Run `env PYSPRAK_PYTHON=PATH/TO/VENV/bin/python spark-submit --master spark://192.168.198.131:7077 keras_spark_mnist.py`.
> * Change `verbose=1` for `hvd.KerasEstimator` to `verbose=3` in `keras_spark_mnist.py` and watch out for `Task service executes command:` log messages and the environment variables used for that command (probably in the executors' stderr log).
> 
> Thanks

Well, there is a change in the output logs but unfortunately got another error....
I ran the following command `env PYSPRAK_PYTHON=/home/orwa/anaconda3/envs/spark1/bin/python spark-submit --master spark://192.168.198.131:7077 keras_spark_mnist.py
` where spark1 is my virtual environment and it looked that it worked but got another exception.
There were many logs in the terminal but I could exclude those that might help:

"[1,3]<stderr>:Exception[1,3]<stderr>:: [1,3]<stderr>:`apply_gradients()` was called without a call to `get_gradients()` or `_aggregate_gradients`. If you're using TensorFlow 2.0, please specify `experimental_run_tf_function=False` in `compile()`.[1,3]<stderr>:

"Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.

mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[57505,1],3]
  Exit code:    1"
...
...
"py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job 3 cancelled part of cancelled job group horovod.spark.run.0"

**Comment by orwa-te** [comment] 2020-06-17 18:32
Also, I tried setting the "`PYSPARK_PYTHON`" in `spark-env.sh` file, increasing the number of **CPUs** of the cluster to **4** and still get the same result with the same error!

**Comment by EnricoMi** [comment] 2020-06-19 04:43
It looks like the `PYSPARK_PYTHON` fixes the original issue for you and now surfaces an unrelated bug. @tgaddair can you elaborate on the `apply_gradients() was called without a call to get_gradients() or _aggregate_gradients` exception?

**Comment by EnricoMi** [comment] 2020-06-19 08:00
@orwa-te can you please provide the full stack trace / more log output of the original error where it complained about `Cannot run program "python": error=2, No such file or directory"`?

**Comment by EnricoMi** [comment] 2020-06-19 08:04
And can you please run the following after undoing your `spark-env.sh` modifications from above?

```
pyspark
>>> def fn(index, _):
...   return [index]
... 
>>> spark.sparkContext.range(0, numSlices=10).mapPartitionsWithIndex(fn).collect()
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

**Comment by orwa-te** [comment] 2020-06-19 10:49
> @orwa-te can you please provide the full stack trace / more log output of the original error where it complained about `Cannot run program "python": error=2, No such file or directory"`?

Check this link for the full stack trace of the logs produced by the command `spark-submit --master spark://192.168.198.131:7077 keras_spark_mnist.py` : [output logs](https://gist.github.com/orwa-te/512674a1e43b52372f2c3f8ba96dca9b)
Keep in mind that in this case `PYSPARK_PYTHON` is removed from `spark-env.sh`.

Setting the `PYSPARK_PYTHON` and executing the same command mentioned above gives the result :[output logs](https://gist.github.com/orwa-te/94dd46c4571b7063de9425fd627ed53e) (the full stack trace)

**Comment by orwa-te** [comment] 2020-06-19 10:59
> And can you please run the following after undoing your `spark-env.sh` modifications from above?
> 
> ```
> pyspark
> >>> def fn(index, _):
> ...   return [index]
> ... 
> >>> spark.sparkContext.range(0, numSlices=10).mapPartitionsWithIndex(fn).collect()
> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
> ```

Whether `PYSPARK_PYTHON` is set or removed from `spark-env.sh` I get the same output for this example:
`[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]`

**Comment by EnricoMi** [comment] 2020-06-19 13:15
Do I understand this right? When you run `spark-submit --master spark://192.168.198.131:7077 keras_spark_mnist.py` without `PYSPARK_PYTHON` in `spark-env.sh` then you get the first provided output logs. When you add `PYSPARK_PYTHON` to `spark-env.sh` you get the `apply_gradients() was called without a call to get_gradients() or _aggregate_gradients` exception?

I would argue that `PYSPARK_PYTHON` needs to be set in `spark-env.sh` to enable your stand alone spark cluster to also run python code, which is a requirement of Horovod to run on your cluster. It looks like `pyspark` does this for you, but spark-submit does not. There is no Python installed on the spark workers machines, only in venvs. Hence `PYSPARK_PYTHON` need to be given to `spark-submit`.

**Comment by orwa-te** [comment] 2020-06-19 16:07
> Do I understand this right? When you run `spark-submit --master spark://192.168.198.131:7077 keras_spark_mnist.py` without `PYSPARK_PYTHON` in `spark-env.sh` then you get the first provided output logs. When you add `PYSPARK_PYTHON` to `spark-env.sh` you get the `apply_gradients() was called without a call to get_gradients() or _aggregate_gradients` exception?
> 
> I would argue that `PYSPARK_PYTHON` needs to be set in `spark-env.sh` to enable your stand alone spark cluster to also run python code, which is a requirement of Horovod to run on your cluster. It looks like `pyspark` does this for you, but spark-submit does not. There is no Python installed on the spark workers machines, only in venvs. Hence `PYSPARK_PYTHON` need to be given to `spark-submit`.

You're right. I will always set `PYSPARK_PYTHON` path when I run the command, but now I am looking forward to seeing a solution to the problem where I got **output logs 2**...... that I linked above...... 
Thanks for your efforts

**Comment by EnricoMi** [comment] 2020-06-19 16:32
Ok, to keep bugs separated I will therefore close this issue. I have created #2041 to track the tensorflow exception.

**Closed by EnricoMi** 2020-06-19 16:32 UTC
Labels: bug
