### ISSUE TITLE
[Question] - Load DistributedTrainer state from a checkpoint on rank 0 and copy it over to all other ranks

### ISSUE THREAD

**Issue by prudhvee** [horovod/horovod#2587] opened 2021-01-10 20:41 UTC
Hey Everyone!!

I am currently saving my DistributedTrainer state from root rank.

```
if hvd.rank() == 0:
     trainer.save_state(<path_to_file>)
```
My question is - when the trainer is initialized from the saved state on root rank, how do I sync/copy the trainer state to other ranks as well. (or do I need not copy the state and hvd will take care of syncing the state?)

Also, I tried loading the trainer state on all the ranks and this created duplicates copies of other PIDs on root rank. I think this is not the correct way to load the state on non-root ranks as it is only loading them onto root rank
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     30880      C   /lib64/ld-linux-x86-64.so.2                 4917MiB |
|    0     30881      C   /lib64/ld-linux-x86-64.so.2                 1409MiB |
|    0     30882      C   /lib64/ld-linux-x86-64.so.2                 1409MiB |
|    0     30883      C   /lib64/ld-linux-x86-64.so.2                 1733MiB |
|    0     30884      C   /lib64/ld-linux-x86-64.so.2                 1409MiB |
|    0     30885      C   /lib64/ld-linux-x86-64.so.2                 1729MiB |
|    0     30886      C   /lib64/ld-linux-x86-64.so.2                 1733MiB |
|    0     30887      C   /lib64/ld-linux-x86-64.so.2                 1797MiB |
|    1     30881      C   /lib64/ld-linux-x86-64.so.2                 3201MiB |
|    2     30882      C   /lib64/ld-linux-x86-64.so.2                 3201MiB |
|    3     30883      C   /lib64/ld-linux-x86-64.so.2                 3201MiB |
|    4     30884      C   /lib64/ld-linux-x86-64.so.2                 3201MiB |
|    5     30885      C   /lib64/ld-linux-x86-64.so.2                 3201MiB |
|    6     30886      C   /lib64/ld-linux-x86-64.so.2                 3201MiB |
|    7     30887      C   /lib64/ld-linux-x86-64.so.2                 3203MiB |
```
Apologies if this has been answered already. I couldn't find references that gives me a confident answer.

Thanks,
Prudhvee.

**Comment by tgaddair** [comment] 2021-01-11 17:00
Hey @prudhvee, can you clarify which framework you're using (TF, PyTorch, MXNet, PyTorch Lightning)?  That'll change the answer.

General rule of thumb is to load saved state on rank 0, create a "new" model / optimizer on the other ranks, and then broadcast model and optimizer parameters from rank 0 to the others.  See [here](https://github.com/horovod/horovod/blob/master/examples/pytorch/pytorch_mnist.py#L173) for a PyTorch example.

**Comment by prudhvee** [comment] 2021-01-11 19:39
Apologies!! I missed that. I am currently using MXNet with Horovod.
Should that be similar to MXNet as well?
I couldn't find corresponding broadcast_optimizer_state in MXNet Horovod docs

**Comment by tgaddair** [comment] 2021-01-12 14:30
Hey @prudhvee, thanks for clarifying.  You're right that we don't have that function for the MXNet API yet (cc @leezu).  However, you can use this function to broadcast the state to all the workers and then load it: https://github.com/horovod/horovod/blob/master/horovod/mxnet/functions.py#L27

For example:

```
if hvd.rank() == 0:
    trainer.load_states(fname)
    with open(fname, 'rb') as f:
        states = f.read()
    hvd.broadcast_object(states)
else:
    states = hvd.broadcast_object(None)
    with tempfile.NamedTemporaryFile() as f:
        f.write(states)
    trainer.load_states(f.name)
```

**Comment by AustinDoolittle** [comment] 2021-01-25 21:02
Hi @tgaddair! I'm working with @prudhvee on this issue. I've implemented the sharing of DistributedTrainer state as you've suggested in your comment, however it still appears that the trainer state in each process is getting loaded onto the root rank's GPU. Is there a way for us to instruct to trainer to load onto the respective rank's GPU?
​
`nvidia-smi` output, for reference:
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     31466      C   /lib64/ld-linux-x86-64.so.2                 4917MiB |
|    0     31467      C   /lib64/ld-linux-x86-64.so.2                 1933MiB |
|    0     31468      C   /lib64/ld-linux-x86-64.so.2                 1665MiB |
|    0     31469      C   /lib64/ld-linux-x86-64.so.2                 1665MiB |
|    0     31470      C   /lib64/ld-linux-x86-64.so.2                 1409MiB |
|    0     31471      C   /lib64/ld-linux-x86-64.so.2                 1409MiB |
|    0     31472      C   /lib64/ld-linux-x86-64.so.2                 1729MiB |
|    0     31473      C   /lib64/ld-linux-x86-64.so.2                 1409MiB |
|    1     31467      C   /lib64/ld-linux-x86-64.so.2                 3201MiB |
|    2     31468      C   /lib64/ld-linux-x86-64.so.2                 3203MiB |
|    3     31469      C   /lib64/ld-linux-x86-64.so.2                 3201MiB |
|    4     31470      C   /lib64/ld-linux-x86-64.so.2                 3201MiB |
|    5     31471      C   /lib64/ld-linux-x86-64.so.2                 3201MiB |
|    6     31472      C   /lib64/ld-linux-x86-64.so.2                 3201MiB |
|    7     31473      C   /lib64/ld-linux-x86-64.so.2                 3203MiB |
+-----------------------------------------------------------------------------+
```

**Comment by tgaddair** [comment] 2021-01-27 17:20
Hey @AustinDoolittle, are you running `mx.gpu(hvd.local_rank())` on each worker?

**Comment by WilliamOnVoyage** [comment] 2021-02-03 17:59
@tgaddair Similar observation as @AustinDoolittle , and yes I'm running `mx.gpu(hvd.local_rank())`, but it is on a single machine.

**Comment by WilliamOnVoyage** [comment] 2021-02-03 18:16
It looks like when loading the trainer state, each rank is not only loading to their own context, but a default "root rank" context, thus we have 8 rank 0 loading + 8 rank <i > loading. (The first rank 0 having a 4900MB usage looks more suspicious because it looks like a "default rank 0" + rank <i> where `i==0`).

So when broadcasting the trainer state to other ranks, how do we check / verify only the corresponding context's state is broadcasted? Or can you point me the source code performing the state loading into context?

**Comment by tgaddair** [comment] 2021-02-08 22:30
@romerojosh @leezu any thoughts on this MXNet issue?

**Comment by AustinDoolittle** [comment] 2021-02-09 18:18
@tgaddair Yes, we are running with the local rank context. You can see in the nvidia-smi output that some memory is allocated for each rank. 

I believe the issue is that MXNet parameters are serialized to disk as a part of the trainer state, and these parameters retain the context they were assigned to when serialized. When they are deserialized, they are loaded back into that context they were set to. The solution is likely to force the parameters to a specific context when they are deserialized in in the `gluon.Trainer`. This might not be feasible with the current interface, as the states are passed to the Trainer as a `bytearray`.

One possible mitigation is to serialize the trainer state on the CPU context, so that they are loaded into host memory initially. They should be moved to the correct context on first update [here](https://github.com/apache/incubator-mxnet/blob/64f737cdd59fe88d2c5b479f25d011c5156b6a8a/python/mxnet/optimizer/optimizer.py#L2099)

**Comment by leezu** [comment] 2021-02-09 19:53
You can set CUDA_VISIBLE_DEVICES in each process to restrict the set of visible GPUs. If each process only sees its own gpu, there can be no leakage to gpu 0.

**Comment by prudhvee** [comment] 2021-02-19 00:44
@leezu 
Would there be any implications on training if we restrict each processes to see its own GPU? For example, for broadcasting model paramters or any other use-case?

**Comment by tgaddair** [comment] 2021-02-19 04:04
Hey @prudhvee, my understanding is that in recent versions of NCCL, there should not be any issue from setting `CUDA_VISIBLE_DEVICES` affecting inter-process communication. So you should be good.

**Comment by prudhvee** [comment] 2021-02-19 05:01
Thanks for confirming. Would you be able to point me to the docs for reference?

**Comment by tgaddair** [comment] 2021-02-19 15:02
Here are the release notes for NCCL 2.4.2 that refer to the ability to set `CUDA_VISIBLE_DEVICES`: https://docs.nvidia.com/deeplearning/nccl/release-notes/rel_2-4-2.html

**Closed** 2021-04-27 22:49 UTC
Labels: wontfix
