### ISSUE TITLE
Upgrade support of newer GCC/G++ compiler

### ISSUE THREAD

**Issue by shailensobhee** [horovod/horovod#1483] opened 2019-10-29 12:43 UTC
**Is your feature request related to a problem? Please describe.**
On newer version of Ubuntu (ex 18.04 or later) or CentOS 8, gcc versions 4.8 or 4.9 are old.
Besides, gcc 4.9 is more than 5 years old. 
One should not see an issue like this on Ubuntu 18.04:
`INFO: Compiler /usr/bin/g++-4.8 (version 4.8.5) is not usable for this TensorFlow installation. Require g++ (version >=4.8.5 20150623 (Red Hat 4.8.5-39), <5).`

**Describe the solution you'd like**
Horovod should compile without problems with GCC 8.3 or later (release date Feb 2019).

**Comment by tgaddair** [comment] 2019-10-29 15:42
Hey @shailensobhee, what version of TensorFlow are you using?  Horovod actually does support newer versions of GCC, but the problem here is that it appears your version of TensorFlow does not.  

Prior to TensorFlow 1.15, TensorFlow binaries were built using G++ 4.X, which is ABI incompatible with G++ 5.X+.  If your version of TensorFlow was built with G++ 4, then we need to use G++ 4 to compile Horovod as well, otherwise things will break at runtime.

See https://github.com/tensorflow/tensorflow/issues/27067 for more info.

**Comment by shailensobhee** [comment] 2019-11-06 17:12
Hello @tgaddair , I'm using Tensorflow 1.14.0 from the anaconda channel.

**Comment by tgaddair** [comment] 2019-11-06 17:37
Thanks for clarifying @shailensobhee.  That makes sense, then.  As I said, the issue is upstream with TensorFlow's binaries themselves, which require using G++ 4.X prior to TensorFlow 1.15.  When you upgrade to a newer version of TensorFlow, this problem will go away.

I'll go ahead and close this issue for now, but feel free to reach out if you have any more questions.

**Closed by tgaddair** 2019-11-06 17:37 UTC
Labels: enhancement

**Comment by vilmara** [comment] 2019-11-12 17:13
hi @tgaddair, I see the Dockerfile.gpu still refers g++-4.8  even though it builds from ubuntu18.04 with TENSORFLOW_VERSION=2.0.0, should the Dockerfile be updated also to use a newer version of g++ ?

**Comment by shailensobhee** [comment] 2020-02-19 17:41
Just in case you came here experiencing a similar problem with Tensorflow >=1.15 on CentOS 7 which ships with an old version of GCC (4.x), here is what you could do to get the latest version of Horovod (v1.19 at the time of writing) to work:

**Steps:**
Install GCC8 toolchain on CentOS 7:

```
sudo yum install centos-release-scl
sudo yum install devtoolset-8-gcc devtoolset-8-gcc-c++
scl enable devtoolset-8 -- bash #sets gcc8 as the default compiler for a session within your current session

env HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITHOUT_PYTORCH=1 pip install --no-cache-dir horovod
```

**Result:**

> [...]Successfully built horovod
> Installing collected packages: horovod
> Successfully installed horovod-0.19.0

**Comment by CaptainDuke** [comment] 2020-04-14 12:26
> Just in case you came here experiencing a similar problem with Tensorflow >=1.15 on CentOS 7 which ships with an old version of GCC (4.x), here is what you could do to get the latest version of Horovod (v1.19 at the time of writing) to work:
> 
> **Steps:**
> Install GCC8 toolchain on CentOS 7:
> 
> ```
> sudo yum install centos-release-scl
> sudo yum install devtoolset-8-gcc devtoolset-8-gcc-c++
> scl enable devtoolset-8 -- bash #sets gcc8 as the default compiler for a session within your current session
> 
> env HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITHOUT_PYTORCH=1 pip install --no-cache-dir horovod
> ```
> 
> **Result:**
> 
> > [...]Successfully built horovod
> > Installing collected packages: horovod
> > Successfully installed horovod-0.19.0

hi I'm installing horovod with tensorflow==1.15.0, and meet same problem.

```
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
g++ (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
mpirun (Open MPI) 4.0.0
tensorflow-gpu == 1.15.0
nccl_2.4.7-1+cuda10.0_x86_64
```
I have tried GCC8 toolchain but it failed either.
```
    Traceback (most recent call last):
      File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 127, in _compile
        extra_postargs)
      File "/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command '/opt/rh/devtoolset-8/root/usr/bin/gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-qhm2qpfe/horovod/setup.py", line 1408, in build_extensions
        build_tf_extension(self, options)
      File "/tmp/pip-install-qhm2qpfe/horovod/setup.py", line 935, in build_tf_extension
        build_ext.build_extension(tensorflow_mpi_lib)
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/usr/lib64/python3.6/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 129, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command '/opt/rh/devtoolset-8/root/usr/bin/gcc' failed with exit status 1
    
    error: None of TensorFlow, PyTorch, or MXNet plugins were built. See errors above.
```
