### ISSUE TITLE
Issues while using Horovod (spark,keras) for distributed training

### ISSUE THREAD

**Issue by Aishwarya2703** [horovod/horovod#2811] opened 2021-04-01 09:33 UTC
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. Spark / PySpark version:
9. Ray version:
10. OS and version:
11. GCC version:
12. CMake version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

I was trying to implement distributed training framework with Horovod (spark , keras ) on MNIST dataset. But facing an issue while fitting the model on training data.

The code is failing at this point of the code -
keras_model = keras_estimator.fit(train_df).setOutputCols(['label_prob'])

And giving following error -
IndexError: list index out of range

RuntimeError: Horovod detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 0
Exit code: 127

I have also set following flags:
os.environ.pop('TF_CONFIG', None)
os.environ['TF_XLA_FLAGS'] = '--tf_xla_enable_xla_devices'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

Refering this code : https://github.com/horovod/horovod/blob/master/examples/spark/keras/keras_spark_mnist.py

Could you help on this ?

**Comment by tgaddair** [comment] 2021-04-12 15:24
Duplicate of #2810. We have this script under test, so it is unlikely to be a bug, so let's triage in the discussion section.

**Closed by tgaddair** 2021-04-12 15:24 UTC
Labels: bug
