### ISSUE TITLE
How to suppress Read -1 stderr error when using horovodrun 

### ISSUE THREAD

**Issue by vbvg2008** [horovod/horovod#1029] opened 2019-04-26 17:21 UTC
Whenever I am using horovodrun on multi-gpu system, I get lots of stderr message like:
`
[1,0]<stderr>:[939debe34dff:00468] Read -1, expected 6441, errno = 1
`
1. what is the root cause of this message? does it from MPI or Horovod? 

2. Is there a way to disable these messages when calling horovodrun?  I know #503 offers a workaround, but I am just wondering if it can be done on the horovod API itself.

**Comment by alsrgv** [comment] 2019-04-30 06:57
@vbvg2008, are you running in Docker containers by any chance?  If so, our [Docker docs](https://github.com/horovod/horovod/blob/master/docs/docker.md#running-on-a-single-machine) suggest running in the privileged mode.

**Comment by vbvg2008** [comment] 2019-04-30 16:10
@alsrgv Thanks for the reply, by any chance you know the cause of that error message?

**Comment by alsrgv** [comment] 2019-05-15 23:17
@vbvg2008, we didn't dig it up too much.  I'm suspecting it's caused by some operation inside NCCL or MPI.

**Comment by vbvg2008** [comment] 2019-05-15 23:58
@alsrgv Thanks for your reply!

**Comment by ChaiBapchya** [comment] 2020-07-08 21:29
Can we open this issue? Since we don't know how it can be suppressed yet?
At times, we don't have the ability to set `privileged` flag due to security reasons.

**Comment by vbvg2008** [comment] 2020-07-08 21:34
re-opening this issue to avoid duplicating issues.     I think this issue is worth looking into for docker users.

**Comment by ChaiBapchya** [comment] 2020-07-08 23:47
duplicate of https://github.com/horovod/horovod/issues/653

**Comment by vycezhong** [comment] 2020-07-20 09:54
add ` 2> /dev/null` to the end of your command. it will disable all stderr messages.

**Closed** 2020-11-13 18:44 UTC
Labels: question, wontfix
