### ISSUE TITLE
spark version 2.3.2 error

### ISSUE THREAD

**Issue by iambyd** [horovod/horovod#2578] opened 2021-01-07 02:59 UTC
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) tensorflow 
2. Framework version:2.3.1
3. Horovod version:0.21.0
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:3.7
8. OS and version:linux
9. GCC version:

if i use spark 2.3.2 then i get a error like this:
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe

and i submit with spark2.4.7, no error

**Comment by tgaddair** [comment] 2021-01-11 16:50
Hey @iambyd, do you need to use Spark 2.3?  Sounds like it may be an issue in Spark fixed in the newer release.

**Comment by EnricoMi** [comment] 2021-01-19 14:52
Yes, I recommend using a newer version of Spark for many reasons. Does your PySpark version match the Spark version of your Spark cluster?

**Comment by EnricoMi** [comment] 2021-01-20 17:13
Do you have and MPI implementation installed? Can you try to build horovod with OpenMPI and run it again with 2.3.2? There might be some Python exception that is the root cause of this generic py4j error. It might not show up with Gloo.

**Closed** 2021-03-27 15:47 UTC
Labels: question, wontfix
