### ISSUE TITLE
local tensor cache hit mechanism

### ISSUE THREAD

**Issue by Tron-x** [horovod/horovod#1582] opened 2019-12-11 08:55 UTC
**Your question:**
I review detail code and I was a little confused. Maybe it was my understanding. I have a problem with the local tensor cache hit mechanism. Is there such a situation? When a sensor fails to hit the local cache, but other processes have hit, it needs to be handed to rank 0 for coordination, but the process that hits the tensor will not send a request to rank 0, So rank 0 can never agree on this tensor,   Doesn't it cause deadlock? Or the current mechanism can fully guarantee the local hit of each tensor

**Comment by tgaddair** [comment] 2019-12-11 16:34
Hey @Tron-x, when you say you have a problem with the cache, are you also seeing incorrect or unexpected behavior, or is it only that you are uncertain how the cache is working?

The cache does a bitwise AND to ensure that all ranks have the tensor cached, so if a tensor fails to hit the local cache on one rank, the other ranks will know that not everyone has that tensor. 

The cache is also guaranteed to have the same tensors represented by the same bits on every worker, because that bit mapping is determined by the Responses sent back from the Coordinator (rank 0).

@romerojosh could give you more details as he designed and implemented the response cache.

**Comment by Tron-x** [comment] 2019-12-12 03:44
hey@Travis Addair，What I'm talking about is the cache miss situation. After the first iteration, all the sensors are miss. But after the first iteration, is there a situation like this? A sensor is hit locally, but some miss, so it's time to give it to rank 0 for coordination. At the same time, the hit sensor will not send a request to rank 0. At this time, the process 0 will not cause deadlock? Because at this time, rank 0 will not collect all requests of this sensor.

**Comment by romerojosh** [comment] 2019-12-12 16:14
Hi @Tron-x. For the cache, there are two scenarios that can occur:
1. If the request is cached: On a given cycle some workers may hit locally while others miss. This is resolved by a bitwise allreduce AND in the cache coordinator which determines if *all* workers report a cache hit for this request. If this is not the case, the request on the workers with the local hit is placed back into the queue to try again on the next cycle. In this way, any cached request is only processed when all workers have it ready to go.
2. If the request does not exist in cache: The uncached request will be passed to rank 0 for coordination. Once all workers submit this uncached request to rank 0, it will form the associated response and send it to all workers for execution. The workers will cache this response for use in subsequent iterations if the response type supported by the cache (supported type is only allreduce currently).

**Comment by Tron-x** [comment] 2019-12-12 16:49
thanks @romerojosh，Is there such a situation? For a request, if some rank is cached locally and some are not, the cached rank will not send a request to process 0, while the uncached rank will send a request to process 0 for coordinate，In this case, rank 0 will not always collect all requests?

**Comment by romerojosh** [comment] 2019-12-12 16:52
The cache is maintained in such a way that it should be globally consistent across workers (i.e. there should be no scenarios where one worker thinks a request is cached while another thinks it is uncached.) If you do run into such a scenario, please let us know because that would be a bug.

**Comment by Tron-x** [comment] 2019-12-12 17:03
Can I understand that for the first training iteration, the local cache table is empty? This is what you call the second situation, "2. If the request does not exist in cache"? , and from the second iteration is what you call the first case: "1.If the request is cached",At this time, the cache table has cached all requests through iteration 1, which can always be cached for all requests (one cycle or multiple cycles)

**Comment by Tron-x** [comment] 2019-12-12 17:04
@romerojosh, Can I understand that :for the first training iteration, the local cache table is empty? This is what you call the second situation, "2. If the request does not exist in cache"? , and from the second iteration is what you call the first case: "1.If the request is cached",At this time, the cache table has cached all requests through iteration 1, which can always be cached for all requests (one cycle or multiple cycles

**Comment by romerojosh** [comment] 2019-12-12 17:07
Yes, that is a correct interpretation.

**Comment by VincentJing** [comment] 2019-12-13 05:13
but I have a question, the cache status have 3 types, HIT  MISS  and INVALID,  if there are only 2 situations as @romerojosh  says, what's the meaning of INVALID ?  HIT  and MISS is enough?

**Comment by romerojosh** [comment] 2019-12-13 17:35
INVALID is the state that is set in order to force workers to evict an existing entry from the cache. This occurs if a request is found in the cache, but the parameters of the cached entry do not match those of the request. We will also invalidate entries that are stalled, in order to force those requests to pass through the coordinator for gathering information for the stall message.

**Comment by VincentJing** [comment] 2019-12-15 06:30
thank you, I see @romerojosh

**Closed** 2020-11-13 22:56 UTC
Labels: question, wontfix
