### ISSUE TITLE
I meet deadlock problem when use horovod.

### ISSUE THREAD

**Issue by xinyual** [horovod/horovod#2506] opened 2020-12-07 13:13 UTC
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet):Mxnet
2. Framework version:2.0
3. Horovod version:0.21.0
4. CUDA version:11.0
5. Python version:3.6
6. GCC version:7.5.0
7. CMake version:3.18.2

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
I have seen the issue #429, but I think my code would not cause different iteration problem mentioned in that issue.

**Bug report:**
[1,0]<stderr>:[2020-12-06 09:54:57.653026: W /tmp/pip-install-i80hmvxk/horovod/horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
[1,0]<stderr>:Missing ranks:
[1,0]<stderr>:5: [horovod_allreduce.157]

**Comment by tgaddair** [comment] 2020-12-07 17:35
Hey @xinyual, can you share a minimal reproducible example?

In general, these errors occur when different Horovod workers are doing different things at the same time.  In your case, it looks like rank 5 is not performing allreduce with the other workers, which may be due to a data imbalance.

**Comment by RickyLLu** [comment] 2020-12-16 14:47
Last time it didn't occur again so I didn't reply you. But thanks for you last response! 
Now it occur again. This time I spend lots of time on data preparing. And the gpu status are shows as follow:
  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     59918      C   python3                          3649MiB |
|    1   N/A  N/A     59919      C   python3                          3793MiB |
|    2   N/A  N/A     59920      C   python3                         10181MiB |
|    3   N/A  N/A     59921      C   python3                         10181MiB |
|    4   N/A  N/A     59922      C   python3                         10181MiB |
|    5   N/A  N/A     59923      C   python3                         10181MiB |
|    6   N/A  N/A     59924      C   python3                         10181MiB |
|    7   N/A  N/A     59925      C   python3                         10037MiB |

And the error report is:
[1,0]<stderr>:[2020-12-16 13:42:03.529383: W /tmp/pip-install-i80hmvxk/horovod/horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock.
[1,0]<stderr>:Missing ranks:
[1,0]<stderr>:0: [horovod_allreduce.0, horovod_allreduce.1, horovod_allreduce.10, horovod_allreduce.100, horovod_allreduce.101, horovod_allreduce.102 ...]
[1,0]<stderr>:1: [horovod_allreduce.0, horovod_allreduce.1, horovod_allreduce.10, horovod_allreduce.100, horovod_allreduce.101, horovod_allreduce.102 ...]
[1,0]<stderr>:2: [horovod_allreduce.0, horovod_allreduce.1, horovod_allreduce.10, horovod_allreduce.100, horovod_allreduce.101, horovod_allreduce.102 ...]

I wonder if reason is that data files are different(some are big while others are small, which means my model needs different time to prepare them)

**Comment by tgaddair** [comment] 2020-12-17 16:07
Hey @RickyLLu, yes that may be the case.  One suggestion would be to add print statements to check where each worker is before model training begins.  If some workers are still preparing data while others have begun training, that would likely be the cause of the issue.

**Comment by RickyLLu** [comment] 2020-12-18 02:50
Yes. I find it is the problem. After I change my way to prepare data, it works. Thanks for your reply! @tgaddair

**Comment by RickyLLu** [comment] 2020-12-18 02:51
Yes, that's the problem. And after changing my way to prepare data, it works well. Thanks for your reply! @tgaddair

**Comment by tgaddair** [comment] 2020-12-18 16:02
Great!  I'll close this issue for now then.

**Closed by tgaddair** 2020-12-18 16:02 UTC
Labels: question

**Comment by huwenyue** [comment] 2021-08-28 14:07
> Yes, that's the problem. And after changing my way to prepare data, it works well. Thanks for your reply! @tgaddair

 
Hi RickyLLu, I have met a similar issue, could you tell me how you fix it?
