### ISSUE TITLE
Missing ranks and deadlock warning

### ISSUE THREAD

**Issue by ashiqimranintel** [horovod/horovod#2565] opened 2020-12-30 23:41 UTC
**Environment:**
1. Framework: Tensorflow
2. Framework version: 2.4
3. Horovod version: 0.21.0
4. MPI version: 3.0.0
5. CUDA version:
6. NCCL version:
7. Python version: 3.7
8. Spark / PySpark version:
9. OS and version: CentOS
10. GCC version: 8.3
11. CMake version:

**Bug report:**
[2020-12-30 16:35:15.181832: W /tmp/pip-req-build-12flcl_u/horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock.
Missing ranks:
1: [DistributedGradientTape_Allreduce/cond_163/then/_1304/DistributedGradientTape_Allreduce/cond_163/HorovodAllreduce_AddN_103_0, DistributedGradientTape_Allreduce/cond_164/then/_1312/DistributedGradientTape_Allreduce/cond_164/HorovodAllreduce_gradient_tape_retinanet_post_hoc_d5_BiasAdd_BiasAddGrad_0, DistributedGradientTape_Allreduce/cond_167/then/_1336/DistributedGradientTape_Allreduce/cond_167/HorovodAllreduce_AddN_105_0, DistributedGradientTape_Allreduce/cond_168/then/_1344/DistributedGradientTape_Allreduce/cond_168/HorovodAllreduce_gradient_tape_retinanet_p6_BiasAdd_BiasAddGrad_0, DistributedGradientTape_Allreduce/cond_173/then/_1384/DistributedGradientTape_Allreduce/cond_173/HorovodAllreduce_AddN_108_0, DistributedGradientTape_Allreduce/cond_174/then/_1392/DistributedGradientTape_Allreduce/cond_174/HorovodAllreduce_gradient_tape_retinanet_p7_BiasAdd_BiasAddGrad_0 ...]

Seeing above messages, any comments why it's showing that?

**Comment by tgaddair** [comment] 2021-01-11 16:26
Duplicate of #2564.

**Closed by tgaddair** 2021-01-11 16:26 UTC
Labels: bug
