### ISSUE TITLE
can XLA_compile=True be used in horovod script to run tf_cnn_benchmark?

### ISSUE THREAD

**Issue by Shuming19** [horovod/horovod#1063] opened 2019-05-10 06:06 UTC
**Environment:**
1. Framework: TensorFlow-GPU
2. Framework version: 1.13.1
3. Horovod version: 0.16.1 with ALLreduce=NCCL
4. MPI version: OpenMPI-4.0.0
5. CUDA version: 10.0
6. NCCL version: 2.4.2
7. Python version: 3.6.8
8. OS and version: Ubuntu 16.04 LTS

**Your question:**
Hello.

tf_cnn_benchmark was tested on our single server equipped with 8 nvidia V100-SXM2 GPUs.

Two scripts are used:
1. using python to run tf_cnn_benchmark with following commands:
  $  python scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py \
        --model resnet101 \
        --batch_size 64 \
        --variable_update=replicated \
        --all_reduce_spec=nccl \
        --xla_compile=True
        --data_dir /path/to/imagenet/tfrecords \
        --data_name imagenet \
        --num_batches=2000

2. using horovod to launch tf_cnn_benchmark:
 $ horovodrun -np 16 -H server1:4,server2:4,server3:4,server4:4 \
    python scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py \
        --model resnet101 \
        --batch_size 64 \
        --variable_update horovod \
        --xla_compile=True
        --data_dir /path/to/imagenet/tfrecords \
        --data_name imagenet \
        --num_batches=2000

The 1st scripts runs fine whereas the 2nd script cannot be implemented with following error:

[1,6]<stderr>:tensorflow.python.framework.errors_impl.InvalidArgumentError: Detected unsupported operations when trying to compile graph tower_0/v0/cluster_10795500259101732890[] on XLA_GPU_JIT: HorovodAllreduce (No registered 'HorovodAllreduce' OpKernel for XLA_GPU_JIT devices compatible with node node tower_0/v0/HorovodAllreduce_tower_0_v0_mul_162_0 (defined at <string>:80) 
[1,6]<stderr>:	.  Registered:  device='GPU'
[1,6]<stderr>:  device='CPU'
[1,6]<stderr>:)node tower_0/v0/HorovodAllreduce_tower_0_v0_mul_162_0 (defined at <string>:80) 
[1,6]<stderr>:	This error might be occurring with the use of xla.compile. If it is not[1,6]<stderr>: necessary that every Op be compiled with XLA, an alternative is to use auto_jit with OptimizerOptions.global_jit_level = ON_2 or the environment variable TF_XLA_FLAGS="tf_xla_auto_jit=2" which will attempt to use xla to compile as much of the graph as the compiler is able to.
[1,6]<stderr>:	 [[tower_0/v0/cluster]]
[1,6]<stderr>:	 [[average_loss/Mean/_2639]]
[1,6]<stderr>:
[1,6]<stderr>:Errors may have originated from an input operation.
[1,6]<stderr>:Input Source operations connected to node tower_0/v0/HorovodAllreduce_tower_0_v0_mul_162_0:
[1,6]<stderr>: tower_0/v0/mul_162 (defined at /home/huawei/benchmarks-cnn_tf_v1.13_compatible/scripts/tf_cnn_benchmarks/benchmark_cnn.py:3231)
[1,6]<stderr>:
[1,6]<stderr>:Input Source operations connected to node tower_0/v0/HorovodAllreduce_tower_0_v0_mul_162_0:
[1,6]<stderr>: tower_0/v0/mul_162 (defined at /home/huawei/benchmarks-cnn_tf_v1.13_compatible/scripts/tf_cnn_benchmarks/benchmark_cnn.py:3231)

When the xla_compile=True is replaced by xla_compile=true, the 2nd script implements fine, however, the throughput drops from 9800 IPS(images per second) to 9600.

Nvidia said that "Horovod and XLA cannot be used together due to a known issue in upstream TensorFlow. We expect this to be resolved in an upcoming release." from https://docs.nvidia.com/deeplearning/dgx/pdf/TensorFlow-Release-Notes.pdf.

My question is can XLA_compile=true be set in horovod script to run tf_cnn_benchmark, please?

Best,
Shuming

**Comment by alsrgv** [comment] 2019-05-10 07:03
@Shuming19, `--xla_compile=True` doesn't work with TF 1.13.x & Horovod, but can you try `--xla=True`?

**Comment by Shuming19** [comment] 2019-05-13 01:37
@alsrgv Thank you for your reply.

I tried --xla=True, and it worked fine. However, the performance(9600 IPS) seems a bit drop(2%) in comparison to  that with --xla_compile=True(9800 IPS).

My question is whether there is any plan that --xla_compile=True will be supported in the next release, please?

Best,
Shuming

**Comment by alsrgv** [comment] 2019-05-13 08:34
@Shuming19, I'm not sure this is caused by `--xla` vs `--xla-compile`.  Can you try specifying `--datasets_num_private_threads=8` when you run Horovod?

**Comment by alsrgv** [comment] 2019-05-13 08:34
cc @karakusc

**Comment by karakusc** [comment] 2019-05-13 18:53
@Shuming19 `xla=True` and `xla_compile=True` should have the same effect in this repository from performance perspective. The performance difference that you are seeing likely is caused by a CPU bottleneck due to Horovod using multiple processes, which can be addressed by limiting the number of threads per process. Can you try setting the flag `dataset_num_private_threads` to the value (number of CPU cores)/8? (i.e. the value you get from`echo $(($(nproc)/8))`)

**Comment by Shuming19** [comment] 2019-05-14 00:58
@karakusc @alsrgv Thank you for your suggestions. The --datasets_num_private_threads=7/4 was set in our test scripts since the total physical core number is 28 with hyperthreading. Still, a performance loss exits.

I just posted a simplified script above to show the problem occurred. The  complete testing script is shown below:

horovodrun -np 32 -H 9.88.35.104:8,9.88.35.65:8,9.88.35.67:8,9.88.35.68:8 --verbose python tf_cnn_benchmarks.py \
  --data_format=NCHW \
  --data_name=imagenet \
  --batch_size=256 \
  --model=resnet50_v1.5 \
  --data_dir=/home/nvme0n1/imagenet \
  --optimizer=momentum \
  --weight_decay=1e-4 \
  --num_warmup_batches=20 \
  --variable_update=horovod \
  --use_fp16=True \
  --nodistortions \
  --gradient_repacking=2 \
  --num_epochs=64 \
  --datasets_num_private_threads=7 \
  --local_parameter_device=gpu \
  --num_gpus=1 \
  --display_every=100 \
  --xla=True \
  --eval_during_training_at_specified_epochs='1,5,9,13,17,21,25,29,33,37,41,45,49,53,57,61,62,,63,64' \
  --num_eval_batches=25 \
  --eval_batch_size=250 \
  --loss_type_to_report=base_loss \
  --single_l2_loss_op \
  --compute_lr_on_cpu \
  --resnet_base_lr=0.06 \
  --datasets_parallel_interleave_cycle_length=20 \
  --datasets_sloppy_parallel_interleave \
  --stop_at_top_1_accuracy=0.70 \
  --print_training_accuracy=True \
  --summary_verbosity=3

According to your experience, there should not be obvious performance gap whether --xla=True or --xla_compile=True is used, is it?

Best,
Shuming

**Comment by Shuming19** [comment] 2019-05-15 02:17
Sorry. I think I did not explain my problem clear enough.

Two scripts were implemented on a single nodes with 8 GPUs. Both complete scripts are listed below:

The 1st one is:
python tf_cnn_benchmarks.py --data_format=NCHW \
  --batch_size=256 \
  --model=resnet50_v1.5 \
  --data_name=imagenet \
  --data_dir=/home/nvme0n1/imagenet \
  --optimizer=momentum \
  --weight_decay=1e-4 \
  --variable_update=replicated \
  --num_warmup_batches=20 \
  --all_reduce_spec=nccl \
  --use_fp16=True \
  --nodistortions \
  --gradient_repacking=2 \
  --num_epochs=64 \
  --ml_perf \
  --local_parameter_device=gpu \
  --num_gpus=8 \
  --display_every=100 \
  --xla=True \
  --datasets_num_private_threads=56 \
  --loss_type_to_report=base_loss \
  --single_l2_loss_op \
  --compute_lr_on_cpu \
  --resnet_base_lr=0.06 \
  --datasets_parallel_interleave_cycle_length=20 \
  --datasets_sloppy_parallel_interleave \
  --print_training_accuracy=True \
  --summary_verbosity=3

The 2nd one is:
horovodrun -np 8 -H localhost:8 --verbose python tf_cnn_benchmarks.py \
  --data_format=NCHW \
  --data_name=imagenet \
  --batch_size=256 \
  --model=resnet50_v1.5 \
  --data_dir=/home/nvme0n1/imagenet \
  --optimizer=momentum \
  --weight_decay=1e-4 \
  --num_warmup_batches=20 \
  --variable_update=horovod \
  --use_fp16=True \
  --nodistortions \
  --gradient_repacking=2 \
  --num_epochs=64 \
  --datasets_num_private_threads=7 \
  --local_parameter_device=gpu \
  --num_gpus=1 \
  --display_every=100 \
  --xla=True \
  --loss_type_to_report=base_loss \
  --single_l2_loss_op \
  --compute_lr_on_cpu \
  --resnet_base_lr=0.06 \
  --datasets_parallel_interleave_cycle_length=20 \
  --datasets_sloppy_parallel_interleave \
  --print_training_accuracy=True \
  --summary_verbosity=3

The throughput of the 1st run is about 10,000 IPS whereas that of the 2nd one is 9200 ips.

And the 2nd run with horovod can not be implemented with --xla_compile=True, otherwise, an error returns as shown above.

Now I was told that horovod cannot be used together with --xla_compile=True. I cannot see any difference between these two runs.

My question is whether the performance gap is caused by --xla_compile/xla=True or not, please?

Also, these two scripts were also used to run on synthetic data to ensure that our CPU is not the performance bottleneck with multi-threading.

Best,
Shuming

**Comment by alsrgv** [comment] 2019-05-15 08:22
@Shuming19,

I've run a couple of experiments on 8xGPU V100 VM in GCP.

`horovodrun -np 8 python tf_cnn_benchmarks.py --model resnet50_v1.5 --data_format=NCHW  --use_fp16=True --variable_update horovod --xla=True --batch_size 256` - 9975.09 img/sec

`python tf_cnn_benchmarks.py --model resnet50_v1.5 --data_format=NCHW  --use_fp16=True --variable_update replicated --all_reduce_spec=nccl --num_gpus=8 --xla=True --batch_size 256` - 8973.12 img/sec

I haven't played with other parameters, they may be able to raise the second option performance, but they may be hard to reproduce for your own models.

**Comment by denfromufa** [comment] 2019-09-11 19:35
@alsrgv for the same settings as above, we are observing 6% degradation when switching from TF parameter server to Horovod. Any ideas?

**Comment by vilmara** [comment] 2020-01-15 18:15
> I've run a couple of experiments on 8xGPU V100 VM in GCP.
> 
> `horovodrun -np 8 python tf_cnn_benchmarks.py --model resnet50_v1.5 --data_format=NCHW --use_fp16=True --variable_update horovod --xla=True --batch_size 256` - 9975.09 img/sec

Hi @alsrgv, did you use a single machine or did you use  8xGPU in distributed mode?. What was the throughput for a 1xGPU?. I have multi-node configuration and the scaling efficiency doesn't look ok, please see below

1xGPU within the node: total images/sec: 1358.21
8xGPU's across the nodes: total images/sec: 9140.62

**Closed** 2020-11-13 22:13 UTC
Labels: question, wontfix

**Comment by surak** [comment] 2022-08-01 18:47
I get this with tensorflow 2.9 and `--xla_compile=True`: 

```python
Node: 'tower_0/v0/HorovodAllreduce_tower_0_v0_mul_2_0'
Detected at node 'tower_0/v0/HorovodAllreduce_tower_0_v0_mul_2_0' defined at (most recent call last):
    File "benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 73, in <module>
      app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
    File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
      _run_main(main, args)
    File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
      sys.exit(main(argv))
    File "benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 68, in main
      bench.run()
    File "/p/project/ccstao/cstao05/tensorflow-2-9-container-test/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1883, in run
      return self._benchmark_train()
    File "/p/project/ccstao/cstao05/tensorflow-2-9-container-test/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2079, in _benchmark_train
      build_result = self._build_graph()
    File "/p/project/ccstao/cstao05/tensorflow-2-9-container-test/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2111, in _build_graph
      (input_producer_op, enqueue_ops, fetches) = self._build_model()
    File "/p/project/ccstao/cstao05/tensorflow-2-9-container-test/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2829, in _build_model
      results = self.add_forward_pass_and_gradients(
    File "/p/project/ccstao/cstao05/tensorflow-2-9-container-test/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3351, in add_forward_pass_and_gradients
      outputs = maybe_compile(forward_pass_and_gradients, self.params)
    File "/p/project/ccstao/cstao05/tensorflow-2-9-container-test/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3546, in maybe_compile
      return tf.xla.experimental.compile(computation)
    File "/p/project/ccstao/cstao05/tensorflow-2-9-container-test/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3276, in forward_pass_and_gradients
      grads = [hvd.allreduce(grad, average=False, device_dense=horovod_device)
    File "/p/project/ccstao/cstao05/tensorflow-2-9-container-test/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3276, in <listcomp>
      grads = [hvd.allreduce(grad, average=False, device_dense=horovod_device)
    File "/usr/local/lib/python3.8/dist-packages/horovod/tensorflow/__init__.py", line 125, in allreduce
      summed_tensor_compressed = _allreduce(tensor_compressed, op=op,
    File "/usr/local/lib/python3.8/dist-packages/horovod/tensorflow/mpi_ops.py", line 127, in _allreduce
      return MPI_LIB.horovod_allreduce(tensor, name=name, reduce_op=op,
    File "<string>", line 107, in horovod_allreduce
Node: 'tower_0/v0/HorovodAllreduce_tower_0_v0_mul_2_0'
2 root error(s) found.
  (0) INVALID_ARGUMENT: Detected unsupported operations when trying to compile graph tower_0/v0/cluster_10200184959390010583[] on XLA_GPU_JIT: HorovodAllreduce (No registered 'HorovodAllreduce' OpKernel for XLA_GPU_JIT devices compatible with node {{node tower_0/v0/HorovodAllreduce_tower_0_v0_mul_2_0}}){{node tower_0/v0/HorovodAllreduce_tower_0_v0_mul_2_0}}
	 [[tower_0/v0/cluster]]
	 [[average_loss/Mean/_557]]
  (1) INVALID_ARGUMENT: Detected unsupported operations when trying to compile graph tower_0/v0/cluster_10200184959390010583[] on XLA_GPU_JIT: HorovodAllreduce (No registered 'HorovodAllreduce' OpKernel for XLA_GPU_JIT devices compatible with node {{node tower_0/v0/HorovodAllreduce_tower_0_v0_mul_2_0}}){{node tower_0/v0/HorovodAllreduce_tower_0_v0_mul_2_0}}
	 [[tower_0/v0/cluster]]
0 successful operations.
```
