### ISSUE TITLE
docker error: signal 11 (Segmentation fault)

### ISSUE THREAD

**Issue by kkk33** [horovod/horovod#1264] opened 2019-07-31 12:42 UTC
**Environment:**
we use the default docker [enviroment](https://raw.githubusercontent.com/horovod/horovod/master/Dockerfile) whose info is as followed:
TENSORFLOW_VERSION=1.14.0
CUDNN_VERSION=7.6.0.64-1+cuda10.0
NCCL_VERSION=2.4.7-1+cuda10.0
python=3.6
gcc=4.8
openmpi=4.0.0

**Your question:**
we start the docker by the command `docker run -it horovod`, and run the example code `horovodrun -np 1 -H localhost:1 python tensorflow_mnist.py`.
but we get the following error `signal 11 (Segmentation fault)`. we search the the error on the website, it comes out that's the problem related to environment edition such as gcc edition etc.
but it's so strange, cause we just use the defalut docker.
we don't know the reason. appreciate for any feedback.

```
[1,0]<stderr>:Fatal Python error: [1,0]<stderr>:Segmentation fault[1,0]<stderr>:
[1,0]<stderr>:
[1,0]<stderr>:Thread 0x[1,0]<stderr>:00007ff05bfff700[1,0]<stderr>: (most recent call first):
[1,0]<stderr>:  File [1,0]<stderr>:"[1,0]<stderr>:/[1,0]<stderr>:u[1,0]<stderr>:s[1,0]<stderr>:r[1,0]<stderr>:/[1,0]<stderr>:lib/python3.6/threading.py", line 295 in wait
[1,0]<stderr>:  File "/usr/lib/python3.6/queue.py", line 164 in get
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/summary/writer/event_file_writer.py", line 159 in run
[1,0]<stderr>:  File "/usr/lib/python3.6/threading.py", line 916 in _bootst[1,0]<stderr>:r[1,0]<stderr>:a[1,0]<stderr>:p_inner
[1,0]<stderr>:  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap
[1,0]<stderr>:
[1,0]<stderr>:Current thread 0x00007ff0cdde1740 (most recent call first):
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1864 in _create_c_op
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensor[1,0]<stderr>:f[1,0]<stderr>:low/python/framework/ops.py", line 2027 in __init__
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3616 in create_op
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorfl[1,0]<stderr>:o[1,0]<stderr>:w/python/util/[1,0]<stderr>:deprecation.py", line 507 in new_func
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788 in _apply_op_helper
[1,0]<stderr>:  File "<string>", line 263 in horovod_broadcast
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/tensorflow/mpi_ops.py", line [1,0]<stderr>:155[1,0]<stderr>: in broadcast
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/tensorflow/__init__.py", line 104 in <listcomp>
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/tensorflow/__init__.py", line 104 in broadcast_variables
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/tensorflow/__init__.py", line 92 in broadcast_global_variables
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/[1,0]<stderr>:t[1,0]<stderr>:e[1,0]<stderr>:nsorflow/__init__.py", line 135 in begin
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow/py[1,0]<stderr>:thon/training/monitored_session.py", line 713 in __init__
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1007 in __init__
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-p[1,0]<stderr>:ackages/tensorflow/python/training/monitored_session.py", line 584 in MonitoredTrainingSession
[1,0]<stderr>:  File "tensorflow_mnist.py", line 152 in main
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251 in _run_main
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300 in run
[1,0]<stderr>:  File "/usr/local/lib/python3.[1,0]<stderr>:6/dist-packages/tensorflow/python/platform/app.py", line 40 in run
[1,0]<stderr>:  File "tensorflow_mnist.py", line 160 in <module>
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node worker1 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

**Comment by liuqi** [comment] 2019-08-22 01:27
This issue should be caused by g++ version detection issue of horovod. It has been fixed in most recent code changes. Could you please try to reinstall from mater?
`HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir git+https://github.com/horovod/horovod`

**Closed** 2020-11-14 01:48 UTC
Labels: question, wontfix
